// ─────────────────────────────────────────────────────────────────────────────
// PETLORE PODCAST AGENCY — Static Demo Data
// 7 example shows + 10 full clip JSON objects
// ─────────────────────────────────────────────────────────────────────────────

// ─── DEMO SHOWS ──────────────────────────────────────────────────────────────

export const DEMO_SHOWS = [
  {
    id: 'show_barks_takes',
    title: 'Barks & Takes',
    tagline: 'The internet had opinions. The dog has corrections.',
    format: 'reddit_reaction',
    host: 'Dexter',
    species: 'dog',
    breed: 'Golden Retriever',
    emoji: '🐕',
    description:
      'A golden retriever reacts to the internet\'s worst takes in real time. Every episode, Dexter reads the most unhinged Reddit threads and gives his unfiltered, extremely confident response.',
    color: 'from-yellow-400 to-orange-500',
    catchphrase: '"With all due respect, that\'s the dumbest thing I\'ve ever heard."',
    sampleClipHook: 'Someone online said dogs can\'t feel love. I need a minute.',
    segments: ['Hot Take Court', 'Dexter\'s Verdict', 'Comment Reaction Wall', 'The Sniff Report'],
    episodes: 47,
    audience: '18-35 dog people who also spend too much time online',
  },
  {
    id: 'show_neighborhood_sniff',
    title: 'The Neighborhood Sniff',
    tagline: 'Local gossip. Zero filter. Maximum snoot.',
    format: 'gossip',
    host: 'Maple',
    species: 'dog',
    breed: 'Beagle',
    emoji: '👃',
    description:
      'A beagle covers the stories your local news won\'t touch. Who left the trash can open? Which squirrel is running for park council? The Sniff has the scoop.',
    color: 'from-green-400 to-teal-500',
    catchphrase: '"My sources are impeccable and I will not reveal them."',
    sampleClipHook: 'The squirrel on Elm Street has been operating without a permit. I have documents.',
    segments: ['This Week in the Yard', 'The Snitch of the Week', 'Weather by Nose', 'Lost & Found Files'],
    episodes: 31,
    audience: 'People who love neighborhood drama and dogs',
  },
  {
    id: 'show_paws_problems',
    title: 'Paws & Problems',
    tagline: 'Bad advice delivered with great confidence.',
    format: 'pet_advice',
    host: 'Professor Biscuit',
    species: 'cat',
    breed: 'Orange Tabby',
    emoji: '🐈',
    description:
      'An orange tabby reads listener problems and delivers terrible but extremely heartfelt advice. He\'s never been right, but he\'s never been more certain.',
    color: 'from-orange-400 to-red-500',
    catchphrase: '"I\'ve never experienced that, but I understand it completely."',
    sampleClipHook: 'You said your relationship has no spark. Have you tried knocking things off shelves?',
    segments: ['Dear Professor', 'The Advice Tribunal', 'This Week\'s Worst Idea', 'Reader Mail'],
    episodes: 62,
    audience: 'Cat people, advice podcast fans, people who enjoy being wrong together',
  },
  {
    id: 'show_daily_biscuit',
    title: 'The Daily Biscuit',
    tagline: 'All the news that\'s fit to sniff.',
    format: 'comedy',
    host: 'Anchor Rusty',
    species: 'dog',
    breed: 'Labrador',
    emoji: '📰',
    description:
      'A labrador explains the news badly but confidently. World events, trending stories, and neighborhood incidents — all filtered through a dog who definitely misunderstood everything.',
    color: 'from-blue-400 to-indigo-500',
    catchphrase: '"We\'re getting reports, and those reports are fascinating."',
    sampleClipHook: 'A man fell asleep at his desk today. Officials are calling it a work-from-home success story.',
    segments: ['Top Stories', 'The Weather Smells', 'Sports (Mostly Fetch)', 'And Finally...'],
    episodes: 88,
    audience: 'Fans of news parody, dog content, and people who love The Daily Show energy',
  },
  {
    id: 'show_unleashed',
    title: 'Unleashed With Sir Barksalot',
    tagline: 'Business advice from a corgi CEO no one asked for.',
    format: 'business_parody',
    host: 'Sir Barksalot',
    species: 'dog',
    breed: 'Corgi',
    emoji: '💼',
    description:
      'A corgi who runs a treat-import business gives LinkedIn-style business advice that nobody requested. He believes in synergy, disruption, and the power of the afternoon nap.',
    color: 'from-purple-400 to-pink-500',
    catchphrase: '"That\'s not a problem, that\'s an opportunity disguised as a problem disguised as a nap."',
    sampleClipHook: 'I just pivoted my entire treat portfolio. Let me walk you through the strategy.',
    segments: ['The Morning Bark', 'Thought Leadership Corner', 'This Week In Synergy', 'CEO Diary'],
    episodes: 24,
    audience: 'LinkedIn-tired millennials, business podcast fans, corgi lovers',
  },
  {
    id: 'show_cat_court',
    title: 'Cat Court',
    tagline: 'Order in the court. The cat is presiding.',
    format: 'gossip',
    host: 'Judge Mittens',
    species: 'cat',
    breed: 'Persian',
    emoji: '⚖️',
    description:
      'A judgmental Persian cat rules on Reddit drama, relationship disputes, and internet controversies. She has read all the evidence. She has made up her mind. You\'re probably wrong.',
    color: 'from-slate-600 to-purple-600',
    catchphrase: '"The court has heard enough. The court is not impressed."',
    sampleClipHook: 'You left your partner on read for three hours. The court rules: justified.',
    segments: ['Opening Arguments', 'The Evidence', 'Judge Mittens Rules', 'Appealed & Denied'],
    episodes: 55,
    audience: 'AITA fans, true crime listeners, people who love judgmental cats',
  },
  {
    id: 'show_squirrel_files',
    title: 'The Squirrel Files',
    tagline: 'They\'re everywhere. They\'re watching. The dog knows.',
    format: 'true_crime_parody',
    host: 'Agent Rex',
    species: 'dog',
    breed: 'German Shepherd',
    emoji: '🔍',
    description:
      'A german shepherd investigates the deepest conspiracies of the neighborhood. Squirrel activity. Suspicious mail carriers. The mystery of the empty food bowl. Agent Rex is on the case.',
    color: 'from-gray-700 to-amber-600',
    catchphrase: '"The squirrel community does not want you to hear this."',
    sampleClipHook: 'Three squirrels. Same tree. No acorns. This is not a coincidence.',
    segments: ['Field Report', 'Surveillance Footage (Described)', 'Known Suspects', 'The Rex Files'],
    episodes: 19,
    audience: 'True crime fans, dog owners, conspiracy comedy listeners',
  },
] as const;

// ─── DEMO CLIPS (10 full ClipJsonScene objects) ───────────────────────────────

export const DEMO_CLIPS = [
  {
    clip_id: 'clip_001',
    show_title: 'Barks & Takes',
    pet_host: 'Dexter',
    episode_title: 'Hot Takes I Cannot Ignore (S2E14)',
    duration_seconds: 32,
    aspect_ratio: '9:16',
    clip_type: 'animated_podcast_clip',
    topic_source: {
      platform: 'reddit',
      source_url: 'https://reddit.com/r/unpopularopinion/comments/example1',
      summary: 'User claims dogs are "just okay" as pets and cats are "objectively superior"',
    },
    hook: 'Someone just posted that dogs are merely "okay." I have thoughts.',
    setup: 'A Reddit user — who I will not name but who is clearly wrong — published a ranked list of pets. Dogs came in third. Behind cats. And behind fish.',
    pet_take: "I\'m not mad. I\'m just deeply, personally, professionally, and emotionally offended. Fish can\'t fetch. Fish have never once been happy to see someone come home. Fish don\'t have takes. I REST MY CASE.",
    punchline: 'Three upvotes. The post got three upvotes. I will allow it. This time.',
    call_to_action: 'Follow Dexter for more internet corrections. He is doing his best.',
    visual_style: 'Pixar-style golden retriever at a podcast desk, Reddit post floating in background, reaction zoom on "objectively superior"',
    character_action: 'Dexter leans into the mic, paw on chest, deeply wounded expression',
    scene_direction: 'Cut to floating Reddit comment cards, waveform animation, reaction zoom on punchline',
    camera: 'Medium close-up, slight zoom on hook line, pull back for punchline',
    audio_direction: 'Confident, slightly indignant tone. Piano riff on punchline. Light crowd murmur.',
    caption: '"Dogs are merely okay." I need a moment. 🐕🎙️',
    hashtags: ['#BarksTakes', '#Dexter', '#PetPodcast', '#DogTok', '#PodcastClip', '#CartoonPet', '#PetloreNetwork', '#UnpopularOpinion'],
    thumbnail_text: '"DOGS ARE MERELY OKAY"',
  },
  {
    clip_id: 'clip_002',
    show_title: 'Cat Court',
    pet_host: 'Judge Mittens',
    episode_title: 'Reddit v. The Read Receipt (S1E8)',
    duration_seconds: 28,
    aspect_ratio: '9:16',
    clip_type: 'animated_podcast_clip',
    topic_source: {
      platform: 'reddit',
      source_url: 'https://reddit.com/r/relationship_advice/comments/example2',
      summary: 'AITA for leaving my partner on read for 4 hours because I was watching a show?',
    },
    hook: 'You left them on read for four hours. You were watching a show. The court is now in session.',
    setup: "The defendant claims they didn\'t see the message. The defendant\'s phone shows 'Read 3:47pm.' The defendant was on episode four of a show they had already seen.",
    pet_take: 'The court acknowledges the show was good. The court has also seen the show. The court watched it in 40 minutes because the court has priorities. The court is a cat.',
    punchline: 'Ruling: reply. Do it now. The court will be watching. The court is always watching.',
    call_to_action: 'New episodes of Cat Court every Tuesday. Justice cannot wait.',
    visual_style: 'Persian cat in judge robes behind a bench, gavel, Reddit thread projected on courtroom screen',
    character_action: 'Judge Mittens peers over tiny glasses, taps gavel once, slowly shakes head',
    scene_direction: 'Courtroom establishing shot, zoom to judge\'s expression, cut to "RULED" verdict card',
    camera: 'Low angle looking up at judge, intimidating framing',
    audio_direction: 'Formal courtroom music, gavel sound, law show-style sting at verdict',
    caption: 'Cat Court is in session. You are probably guilty. ⚖️🐈',
    hashtags: ['#CatCourt', '#JudgeMittens', '#AITA', '#PetPodcast', '#CartoonCat', '#PetloreNetwork', '#RelationshipAdvice', '#CatTok'],
    thumbnail_text: 'COURT IS IN SESSION',
  },
  {
    clip_id: 'clip_003',
    show_title: 'Unleashed With Sir Barksalot',
    pet_host: 'Sir Barksalot',
    episode_title: 'Q3 Treat Strategy & Q4 Snack Pipeline (S1E3)',
    duration_seconds: 35,
    aspect_ratio: '9:16',
    clip_type: 'animated_podcast_clip',
    topic_source: {
      platform: 'reddit',
      source_url: 'https://reddit.com/r/LinkedInLunatics/comments/example3',
      summary: 'LinkedIn post about hustle culture and "eating last" leadership philosophy',
    },
    hook: "I just read a LinkedIn post about 'eating last.' As a corgi, I have concerns.",
    setup: "The post says great leaders eat last. The post has 47,000 likes. The post was clearly written by someone who has never been fed at 6:02pm instead of 6:00pm.",
    pet_take: "In my organization, everyone eats first and I eat continuously. That\'s not a leadership style. That\'s just correct. We\'ve had zero attrition. Mostly because no one can leave. But the vibe is excellent.",
    punchline: "I will be sharing this post with my team. My team is a stuffed bear named Gerald. Gerald agrees with me on everything. Gerald is employee of the month every month.",
    call_to_action: "Subscribe for weekly business insights from a corgi who is thriving. Unleashed drops every Monday.",
    visual_style: 'Corgi in tiny suit at a standing desk, LinkedIn post on screen behind him, motivational posters featuring treats',
    character_action: 'Sir Barksalot adjusts tie, gestures at whiteboard with quarterly treat chart',
    scene_direction: 'Corporate office aesthetic, zoom into ridiculous LinkedIn post, reaction cut to corgi looking directly at camera',
    camera: 'Eye-level medium shot, slight dolly push on punchline',
    audio_direction: 'Corporate upbeat music, slight cringe sting at LinkedIn mention',
    caption: 'Corgi CEO breaks down the leadership crisis of our time 💼🐕',
    hashtags: ['#SirBarksalot', '#CorgoCEO', '#LinkedInLunatics', '#PetPodcast', '#BusinessAdvice', '#PetloreNetwork', '#CartoonPet', '#WorkHumor'],
    thumbnail_text: 'CORGI CEO EXPLAINS IT ALL',
  },
  {
    clip_id: 'clip_004',
    show_title: 'Paws & Problems',
    pet_host: 'Professor Biscuit',
    episode_title: 'Your Life Is Fixable (Probably) (S3E22)',
    duration_seconds: 30,
    aspect_ratio: '9:16',
    clip_type: 'animated_podcast_clip',
    topic_source: {
      platform: 'reddit',
      source_url: 'https://reddit.com/r/relationship_advice/comments/example4',
      summary: 'User asks how to reconnect with their partner after a big fight',
    },
    hook: 'You want to reconnect after a fight. Have you tried sitting on their laptop?',
    setup: "The listener writes: we had a big argument and there\'s been distance ever since. How do I close the gap? First of all, what gap? Gaps are for sitting in.",
    pet_take: "I have solved every conflict in my household by sitting on whatever the human was looking at. Phone? Sit. Book? Sit. Feelings? Sit. This is not a metaphor. Well, it\'s a little bit of a metaphor. Sit on the feelings.",
    punchline: "Update me. I won\'t remember but I\'ll pretend I do and I\'ll be very proud of you.",
    call_to_action: 'DM Paws & Problems with your problems. We read everything. We solve nothing. But we try.',
    visual_style: 'Orange tabby in professor glasses behind a cozy desk, warm lamp, "PROFESSOR BISCUIT" nameplate, listener letter on screen',
    character_action: 'Professor Biscuit pushes glasses up with one paw, nods gravely, looks at camera',
    scene_direction: 'Warm library aesthetic, letter fades in on screen, zoom to Biscuit\'s thoughtful expression',
    camera: 'Intimate medium close-up, shallow depth of field, warm tones',
    audio_direction: 'Soft piano, advice podcast tone, slight comedy timing pause before punchline',
    caption: 'The Professor has spoken. Results may vary. 🐈📬',
    hashtags: ['#PawsAndProblems', '#ProfBiscuit', '#AdvicePodcast', '#CatAdvice', '#PetPodcast', '#PetloreNetwork', '#RelationshipAdvice', '#CatTok'],
    thumbnail_text: 'HAVE YOU TRIED SITTING ON IT?',
  },
  {
    clip_id: 'clip_005',
    show_title: 'The Neighborhood Sniff',
    pet_host: 'Maple',
    episode_title: 'The Squirrel Council Convenes (S2E5)',
    duration_seconds: 27,
    aspect_ratio: '9:16',
    clip_type: 'animated_podcast_clip',
    topic_source: {
      platform: 'reddit',
      source_url: 'https://reddit.com/r/neighbors/comments/example5',
      summary: 'Neighbor dispute over a tree that\'s dropping leaves onto someone else\'s property',
    },
    hook: 'The leaves from 14 Oak Street are crossing the property line. This has escalated.',
    setup: "My sources — who are three birds and a fence post — confirm that the maple tree at 14 Oak has been shedding in violation of the informal yard agreement of autumn 2021.",
    pet_take: "The resident of 16 Oak has filed a formal grievance using a note. A handwritten note. On paper. We haven\'t seen paper since the July incident. Things are very serious.",
    punchline: "I\'ve reached out to the squirrel council for comment. They were unavailable. The squirrel council is never available. Suspicious.",
    call_to_action: 'Follow The Neighborhood Sniff. Breaking local stories. Impeccable sources.',
    visual_style: 'Beagle at a newsroom desk, neighborhood map behind her, "BREAKING" chyron, tree diagram',
    character_action: 'Maple shuffles papers importantly, looks at camera, sniffs the air once mid-sentence',
    scene_direction: 'TV news parody setup, lower thirds for "sources," cut to neighborhood aerial map',
    camera: 'News anchor medium shot, cut to full-screen map graphic',
    audio_direction: 'Local news theme, urgent music sting, serious anchor tone',
    caption: 'Breaking: the leaves have crossed the line. 📰👃 #LocalNews',
    hashtags: ['#NeighborhoodSniff', '#Maple', '#LocalNews', '#BeaglePodcast', '#PetPodcast', '#PetloreNetwork', '#NeighborDrama', '#DogTok'],
    thumbnail_text: 'LEAVES CROSSING THE LINE',
  },
  {
    clip_id: 'clip_006',
    show_title: 'The Daily Biscuit',
    pet_host: 'Anchor Rusty',
    episode_title: 'Monday News Roundup (S1E34)',
    duration_seconds: 29,
    aspect_ratio: '9:16',
    clip_type: 'animated_podcast_clip',
    topic_source: {
      platform: 'reddit',
      source_url: 'https://reddit.com/r/mildlyinfuriating/comments/example6',
      summary: 'Person complains their co-worker microwaves fish in the office every single day',
    },
    hook: "Breaking news: a man is microwaving fish at work. Authorities are baffled. I am not.",
    setup: "Reports confirm the fish has been microwaved on 14 consecutive Tuesdays. Colleagues have filed formal complaints. The man has not been reached for comment. He cannot smell anything.",
    pet_take: "I want to be clear: as a labrador, I am supportive of fish-related activities in the workplace. My position on this is complicated. I\'m exploring a range of emotions.",
    punchline: "The fish will continue. The office will adapt. This is the Tuesday cycle. We are all living in it.",
    call_to_action: "The Daily Biscuit. All the news that\'s fit to sniff. New episode every morning.",
    visual_style: 'Labrador in news anchor suit, Breaking News chyron, stock photo of microwave in background',
    character_action: 'Anchor Rusty looks directly at camera with professional concern, shuffles papers, sniffs air',
    scene_direction: 'News desk setup, cut to "OFFICE FISH REPORT" graphic, back to anchor for punchline',
    camera: 'Standard news anchor framing, occasional cut-away graphic',
    audio_direction: 'News broadcast music, serious anchor voice that barely conceals excitement about the fish',
    caption: 'The fish story we cannot ignore. 🐟📺 #BreakingNews',
    hashtags: ['#DailyBiscuit', '#AnchorRusty', '#OfficeNews', '#PetPodcast', '#PetloreNetwork', '#MildlyInfuriating', '#CartoonDog', '#DogTok'],
    thumbnail_text: 'FISH MICROWAVED AGAIN',
  },
  {
    clip_id: 'clip_007',
    show_title: 'The Squirrel Files',
    pet_host: 'Agent Rex',
    episode_title: 'Operation: Empty Feeder (S1E6)',
    duration_seconds: 33,
    aspect_ratio: '9:16',
    clip_type: 'animated_podcast_clip',
    topic_source: {
      platform: 'reddit',
      source_url: 'https://reddit.com/r/birding/comments/example7',
      summary: 'Bird feeder keeps being emptied overnight, suspected squirrel activity',
    },
    hook: "The bird feeder at 22 Maple has been completely emptied. Third time this week. This is not an accident.",
    setup: "Field report from Tuesday 0600 hours: feeder full. Field report from Tuesday 0800 hours: feeder empty. No birds sighted. No trace evidence. I have been watching from my surveillance post, which is the window.",
    pet_take: "The squirrel community operates in coordinated units. I\'ve been saying this for years. The humans call me 'worked up.' The humans have not seen what I have seen.",
    punchline: "I don\'t have proof yet. But I have a feeling, and my feelings have a perfect investigative record. Mostly.",
    call_to_action: "The Squirrel Files drops new cases every Thursday. Agent Rex is still on duty.",
    visual_style: 'German shepherd in trench coat at a conspiracy board, red string connecting bird feeder photo to squirrel mugshots',
    character_action: 'Agent Rex taps the conspiracy board, looks over shoulder suspiciously, speaks just above a whisper',
    scene_direction: 'Dark investigation room aesthetic, close-up of evidence board, dramatic reveal zoom',
    camera: 'Low lighting, handheld feel, close-up on eyes during serious parts',
    audio_direction: 'True crime podcast music, hushed serious tone, dramatic bass note on reveal',
    caption: 'The squirrel community does not want you to hear this. 🔍🐿️',
    hashtags: ['#SquirrelFiles', '#AgentRex', '#TrueCrime', '#PetPodcast', '#PetloreNetwork', '#ConspiracyDog', '#GermanShepherd', '#DogDetective'],
    thumbnail_text: 'THEY TOOK THE SEEDS',
  },
  {
    clip_id: 'clip_008',
    show_title: 'Barks & Takes',
    pet_host: 'Dexter',
    episode_title: 'The Monday Mailbag (S3E2)',
    duration_seconds: 26,
    aspect_ratio: '9:16',
    clip_type: 'animated_podcast_clip',
    topic_source: {
      platform: 'reddit',
      source_url: 'https://reddit.com/r/todayilearned/comments/example8',
      summary: "TIL dogs can smell cancer and have a 97% accuracy rate",
    },
    hook: 'I just learned dogs can smell cancer with 97% accuracy. I have never been more vindicated in my entire life.',
    setup: "For years — years — I have been telling people that my nose is a precision medical instrument. 'Stop sniffing strangers, Dexter.' 'Get out of the pantry, Dexter.' Turns out: I was doing diagnostics.",
    pet_take: "Ninety-seven percent. You want to know what doctors get? I looked it up. Significantly less confident. No offense to doctors. Some of my best friends are vets. I\'ve been wrong about the vet.",
    punchline: "I accept your apologies. You can submit them in the comments or by throwing a ball. Either works.",
    call_to_action: 'Barks & Takes. Where the internet gets the corrections it deserves.',
    visual_style: 'Golden retriever at desk, scientific-looking charts behind him, "DOCTOR DEXTER" placard',
    character_action: 'Dexter straightens posture, very proud, taps desk with paw for emphasis',
    scene_direction: 'Cut between scientific graphic and Dexter\'s triumphant expression',
    camera: 'Medium shot, slight upward angle to emphasize vindication',
    audio_direction: 'Triumphant horn sting on reveal, confident tone throughout',
    caption: '97% accuracy. I accept apologies. 🐕🔬 #Vindicated',
    hashtags: ['#BarksTakes', '#Dexter', '#TodayILearned', '#DogScience', '#PetPodcast', '#PetloreNetwork', '#GoldenRetriever', '#DogFacts'],
    thumbnail_text: '97% ACCURACY. TOLD YOU.',
  },
  {
    clip_id: 'clip_009',
    show_title: 'Paws & Problems',
    pet_host: 'Professor Biscuit',
    episode_title: 'Modern Friendship & Why It Is Broken (S4E7)',
    duration_seconds: 31,
    aspect_ratio: '9:16',
    clip_type: 'animated_podcast_clip',
    topic_source: {
      platform: 'reddit',
      source_url: 'https://reddit.com/r/friendship/comments/example9',
      summary: "User asks why making friends as an adult feels impossible",
    },
    hook: "Making friends as an adult is hard. Making friends as a cat is also hard, but different.",
    setup: "A listener writes: I\'m 32, I work from home, and I have not made a new friend in four years. How do I fix this? The Professor has heard this before.",
    pet_take: "Here is my method. I sit near people. I do not look at them directly. I do not speak. I simply exist in their general vicinity until the friendship forms naturally or doesn\'t. This has a 40% success rate. For a cat, this is exceptional.",
    punchline: "The other 60% think I\'m judging them. I am. But that\'s not the point.",
    call_to_action: 'Paws & Problems. We are working through it together. Mostly alone, but together.',
    visual_style: 'Orange tabby professor leaning back in chair, warm bookshelf behind, listener letter on desk',
    character_action: 'Professor Biscuit touches tips of paws together, considering deeply, slow blink at camera',
    scene_direction: 'Intimate therapy-office aesthetic, soft zoom on letter, Biscuit\'s expression going from serious to slightly smug',
    camera: 'Close-up on Biscuit\'s face during punchline delivery',
    audio_direction: 'Soft jazz, considered timing, slight warm music swell under punchline',
    caption: "The Professor\'s friendship method: 40% success rate. He stands by it. 🐈📬",
    hashtags: ['#PawsAndProblems', '#ProfBiscuit', '#AdultFriendship', '#CatAdvice', '#PetPodcast', '#PetloreNetwork', '#CatTok', '#MentalHealth'],
    thumbnail_text: 'WHY ADULTS HAVE NO FRIENDS',
  },
  {
    clip_id: 'clip_010',
    show_title: 'Unleashed With Sir Barksalot',
    pet_host: 'Sir Barksalot',
    episode_title: 'The Morning Routine That Changed Everything (S2E1)',
    duration_seconds: 34,
    aspect_ratio: '9:16',
    clip_type: 'animated_podcast_clip',
    topic_source: {
      platform: 'reddit',
      source_url: 'https://reddit.com/r/productivity/comments/example10',
      summary: "Post about 5am morning routines and their effect on professional success",
    },
    hook: "I wake up at 5am every day. Not by choice. Breakfast is at 5am. But I\'ve reframed it as a competitive advantage.",
    setup: "Productivity influencers say waking up early is the secret to success. I have been doing this for three years. I did not choose this. A corgi\'s internal clock is non-negotiable. But I\'ve been taking credit for it.",
    pet_take: "5am: awake. 5:02am: breakfast secured. 5:10am: lap completed. 5:15am: back asleep until 9. This is my morning routine. I have a Forbes profile somewhere. Probably.",
    punchline: "The key to my success is simple: I outsourced my entire breakfast operation to a human who loves me unconditionally. This is called strategic delegation. I recommend it.",
    call_to_action: 'Unleashed with Sir Barksalot. Business insights. Every Monday. Whether you asked or not.',
    visual_style: 'Corgi CEO at standing desk, morning light through office window, motivational poster reading "BREAKFAST IS NON-NEGOTIABLE"',
    character_action: 'Sir Barksalot gestures at sunrise photo on wall, adjusts tiny tie, very self-satisfied expression',
    scene_direction: 'Morning-vibe warmth, motivational overlay text, reaction zoom on "strategic delegation"',
    camera: 'Confident medium shot, dolly push during "competitive advantage" line',
    audio_direction: 'Motivational morning podcast energy, triumphant sting on delegation line',
    caption: 'The 5am routine no one asked about. He will explain it. 💼🐕',
    hashtags: ['#SirBarksalot', '#MorningRoutine', '#CorgoCEO', '#ProductivityTips', '#PetPodcast', '#PetloreNetwork', '#CorgiTok', '#BusinessAdvice'],
    thumbnail_text: '5AM WAKE UP (NOT BY CHOICE)',
  },
] as const;

// ─── VET NEWSLETTER DEMO DATA ─────────────────────────────────────────────────

export const DEMO_VET_NEWSLETTERS = [
  {
    id: 'nsl_001',
    clinicName: 'Blue Ridge Animal Hospital',
    city: 'Asheville',
    state: 'NC',
    newsletterName: 'The Biscuit Bulletin',
    issueNumber: 12,
    theme: 'Dental Health Month',
    subjectLine: "🦷 February is Dental Month — and Biscuit has something to say",
    sections: [
      { type: 'funny_story', headline: 'Biscuit Tried to Floss. It Did Not Go Well.', body: 'Our cartoon host attempted dental hygiene for the first time this week. Results: inconclusive. Lesson: start your pet early. Book a dental cleaning before February 28 and save 15%.' },
      { type: 'health_tip', headline: '3 Signs Your Pet Needs a Dental Check', body: 'Bad breath, pawing at mouth, and changes in eating habits are the top three signals. Any of these sound familiar? Call us — it\'s more common than you think.' },
      { type: 'pet_spotlight', headline: 'Pet of the Month: Mochi the Shih Tzu', body: 'Mochi came in with a serious dental issue in January. She left with a clean bill of health and is now back to stealing socks with full confidence.' },
    ],
  },
  {
    id: 'nsl_002',
    clinicName: 'Parkside Pet Wellness',
    city: 'Austin',
    state: 'TX',
    newsletterName: 'Tail Talk Weekly',
    issueNumber: 7,
    theme: 'Spring Flea & Tick Season',
    subjectLine: "🌸 Spring is here. So are the fleas. Dexter has thoughts.",
    sections: [
      { type: 'seasonal_alert', headline: "Flea Season Starts NOW in Central Texas", body: "Central Texas flea season kicked off early this year. If your pet isn\'t on preventatives, now is the time. We have 3 great options — ask us which one is right for your pet\'s lifestyle." },
      { type: 'podcast_clip', headline: "Dexter\'s Hot Take on Fleas", body: '"Fleas are the content creators of the pest world. Nobody asked for them. They appear uninvited. They overstay their welcome. I have never respected them." — Dexter, Barks & Takes Ep. 52' },
      { type: 'health_tip', headline: 'The 3-Step Spring Check', body: 'Before every walk: quick flea comb, check the ears, look between the toes. Takes 60 seconds. Saves you a vet visit. You\'re welcome.' },
    ],
  },
];

// ─── PODCAST FORMAT OPTIONS ──────────────────────────────────────────────────

export const PODCAST_FORMATS = [
  { id: 'comedy', label: 'Comedy Podcast', emoji: '😂', description: 'Pure entertainment and character-driven humor' },
  { id: 'gossip', label: 'Gossip & Drama', emoji: '👀', description: 'React to drama, disputes, and internet mess' },
  { id: 'motivational', label: 'Motivational', emoji: '💪', description: 'Your pet hypes up the audience with absurd confidence' },
  { id: 'pet_advice', label: 'Pet Advice', emoji: '🐾', description: 'Terrible but heartfelt advice from your pet' },
  { id: 'neighborhood_news', label: 'Neighborhood News', emoji: '📰', description: 'Hyper-local gossip, very serious delivery' },
  { id: 'reddit_reaction', label: 'Reddit Reaction', emoji: '📱', description: 'Your pet reacts to the internet\'s worst takes' },
  { id: 'sports_takes', label: 'Sports Takes', emoji: '🏆', description: 'Hot sports opinions from a pet with no qualifications' },
  { id: 'relationship_advice', label: 'Relationship Advice', emoji: '💌', description: 'Love and friendship guidance from your pet' },
  { id: 'true_crime_parody', label: 'True Crime Parody', emoji: '🔍', description: 'Neighborhood mysteries, investigated seriously' },
  { id: 'business_parody', label: 'Business Parody', emoji: '💼', description: 'LinkedIn energy. Pet-sized authority. Zero credentials.' },
  { id: 'bedtime', label: 'Bedtime Show', emoji: '🌙', description: 'Calm, cozy, oddly relaxing' },
  { id: 'kids_family', label: 'Kids & Family', emoji: '👨‍👩‍👧', description: 'Wholesome, funny, safe for tiny humans' },
] as const;
